spring:
  application:
    name: spring-database-sharding

  datasource:
    shard1:
      jdbc-url: jdbc:postgresql://localhost:5432/shard1-db-test
      username: postgres
      password: postgres
      driver-class-name: org.postgresql.Driver

    shard2:
      jdbc-url: jdbc:postgresql://localhost:5432/customer_db_shard2
      username: postgres
      password: postgres
      driver-class-name: org.postgresql.Driver
    hikari:
      maximum-pool-size: 10
      minimum-idle: 5
      idle-timeout: 30000
      max-lifetime: 600000

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true
        dialect: org.hibernate.dialect.PostgreSQLDialect

server:
  port: 8081

  # enable payload (response) compression to improve faster response
  # mine-types: content types to be compressed
  # min-response-size: limit the min size for compression on response
  compression:
    enabled: true
    mime-types: application/json
    min-response-size: 512

management:
  endpoints:
    web:
      exposure:
        include:
          - health
          - info
          - metrics
  health:
    show-details: always
  metrics:
    enable:
      hikari: true